# create_project.tcl
#
# Recreates the Vivado project for the XEM7305 pulse-sequencer port from
# checked-in sources. Run from within this directory:
#
#   vivado -mode batch -source create_project.tcl
#
# Part: xc7s50csga324-1, matching Locally_compiled_ramtester (../XEM7305_references)
# and the "Device:" comment embedded in the encrypted OK IP netlists copied
# into src/ (e.g. src/okWireIn.v). Locally_compiled_photon_2026 targeted
# csga324-2 instead — confirm which speed grade your actual XEM7305 board
# uses before building for hardware; change PART below if -2 is correct.

set PART "xc7s50csga324-1"
set PROJ_NAME "xem7305_pulser"
set PROJ_DIR  "./build"

create_project $PROJ_NAME $PROJ_DIR -part $PART -force
set_property target_language VHDL [current_project]

# Phase 2/6: Clocking Wizard (MMCM) IP, replacing the legacy design's
# clk_pll_100_in_200_out. Same three output frequencies (200/100/20 MHz)
# and roles (PMT oversampling / main state machine / DDS+line-trigger).
#
# Phase 6 (DDR3 migration) re-sources this from MIG's ui_clk instead of
# the XEM7305's raw 200 MHz sys_clk: MIG (src/ip/ddr3_256_16) now owns
# the physical sys_clk_p/sys_clk_n differential pins directly (its
# System Clock config is Differential, matching the proven
# Locally_compiled_ramtester reference -- see AR#45588 on why System
# Clock=No Buffer + a separate IBUFGDS couldn't be validated instead).
# ui_clk = 200 MHz * CLKFBOUT_MULT(13) / DIVCLK_DIVIDE(2) / CLKOUT3_DIVIDE(16)
#        = 81.25 MHz exactly (confirmed from ddr3_256_16_mig.vhd's generics).
# PRIM_SOURCE is No_buffer (not Single_ended_clock_capable_pin) because
# ui_clk is an already-BUFG'd internal fabric net from MIG, not a raw
# external pin -- clk_wiz_0 must not add its own IBUF/pin buffer for it.
# 81.25 MHz doesn't divide the MMCM's 0.125-step multiply grid evenly
# back into exact 200/100/20 MHz (the /2/16 factors reintroduce a /13
# that doesn't fit within CLKFBOUT_MULT_F's <=64 limit), so expect a
# small (sub-0.1%, likely sub-0.01%) output frequency error -- check
# the actual vs. requested frequencies Vivado reports after generating.
create_ip -name clk_wiz -vendor xilinx.com -library ip -module_name clk_wiz_0 -dir ./src/ip
set_property -dict [list \
    CONFIG.PRIM_IN_FREQ {81.250} \
    CONFIG.PRIM_SOURCE {No_buffer} \
    CONFIG.CLKOUT1_USED {true} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {200.000} \
    CONFIG.CLKOUT2_USED {true} \
    CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {100.000} \
    CONFIG.CLKOUT3_USED {true} \
    CONFIG.CLKOUT3_REQUESTED_OUT_FREQ {20.000} \
    CONFIG.NUM_OUT_CLKS {3} \
    CONFIG.USE_LOCKED {true} \
    CONFIG.USE_RESET {false} \
] [get_ips clk_wiz_0]
generate_target {instantiation_template synthesis simulation} [get_files ./src/ip/clk_wiz_0/clk_wiz_0.xci]

# ---------------------------------------------------------------------------
# Remaining IP (config captured from the working 2025.2 build via
# `write_ip_tcl`). Creating them here fixes the Mac<->Windows divergence where
# the IP had to be regenerated by hand. Requires the Vivado IP catalog to have
# fifo_generator 13.2, mig_7series 4.2 and blk_mem_gen 8.4 (Vivado 2025.2).
# ---------------------------------------------------------------------------

# Phase 6a: DDR3 SDRAM controller (Xilinx MIG 7-series). Its customization is
# imported from the checked-in MIG project file (src/ip_cfg/ddr3_256_16.prj,
# copied verbatim from the proven Locally_compiled_ramtester reference) rather
# than the absolute path the Vivado GUI records -- so the controller is
# reproducible on any machine. MT41K256M16XX-125, MEM_ADDR_ORDER
# BANK_ROW_COLUMN, System Clock = Differential (MIG owns sys_clk_p/sys_clk_n).
create_ip -name mig_7series -vendor xilinx.com -library ip -version 4.2 -module_name ddr3_256_16 -dir ./src/ip
set_property CONFIG.XML_INPUT_FILE [file normalize ./src/ip_cfg/ddr3_256_16.prj] [get_ips ddr3_256_16]
generate_target {instantiation_template synthesis simulation} [get_files ./src/ip/ddr3_256_16/ddr3_256_16.xci]

# Phase 6b: DDR3 read-prefetch FIFO -- 128-bit write / 32-bit read Standard
# FIFO (NOT FWFT), independent clocks. The read-prefetch pushes each whole
# 128-bit MIG response in one write; the FIFO does the 128->32 conversion.
create_ip -name fifo_generator -vendor xilinx.com -library ip -version 13.2 -module_name ddr3_read_fifo -dir ./src/ip
set_property -dict [list \
  CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
  CONFIG.Input_Data_Width {128} \
  CONFIG.Input_Depth {256} \
  CONFIG.Output_Data_Width {32} \
  CONFIG.Performance_Options {Standard_FIFO} \
  CONFIG.Read_Data_Count {true} \
  CONFIG.Write_Data_Count {true} \
] [get_ips ddr3_read_fifo]
generate_target {instantiation_template synthesis simulation} [get_files ./src/ip/ddr3_read_fifo/ddr3_read_fifo.xci]

# Phase 6c: DDR3 line-streamer prefetch FIFO -- 128-bit write / 64-bit read
# Standard FIFO, independent clocks (ui_clk write, clk_100 read). One 128-bit
# MIG beat becomes two 64-bit program lines; ddr3_line_streamer writes whole
# beats, pulse_sequencer pops one 64-bit line at a time. Must match the
# 128/64 Standard-FIFO ports the streamer declares (full/empty/wr_data_count/
# rd_data_count) and the LOW-first half ordering assumed by the sequencer.
create_ip -name fifo_generator -vendor xilinx.com -library ip -version 13.2 -module_name line_fifo_128x64 -dir ./src/ip
set_property -dict [list \
  CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
  CONFIG.Input_Data_Width {128} \
  CONFIG.Input_Depth {256} \
  CONFIG.Output_Data_Width {64} \
  CONFIG.Performance_Options {Standard_FIFO} \
  CONFIG.Read_Data_Count {true} \
  CONFIG.Write_Data_Count {true} \
] [get_ips line_fifo_128x64]
generate_target {instantiation_template synthesis simulation} [get_files ./src/ip/line_fifo_128x64/line_fifo_128x64.xci]

# Phase 6b: DDR3 write FIFO -- 64-bit FWFT, independent clocks. The write
# assembler reads 64-bit words and pairs two into one 128-bit MIG write.
create_ip -name fifo_generator -vendor xilinx.com -library ip -version 13.2 -module_name ddr3_write_fifo -dir ./src/ip
set_property -dict [list \
  CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
  CONFIG.Input_Data_Width {64} \
  CONFIG.Input_Depth {32} \
  CONFIG.Performance_Options {First_Word_Fall_Through} \
  CONFIG.Read_Data_Count {true} \
] [get_ips ddr3_write_fifo]
generate_target {instantiation_template synthesis simulation} [get_files ./src/ip/ddr3_write_fifo/ddr3_write_fifo.xci]

# Phase 3/4 readout + pulse FIFOs and program RAM (legacy design IP).
create_ip -name fifo_generator -vendor xilinx.com -library ip -version 13.2 -module_name fifo_photon -dir ./src/ip
set_property -dict [list \
  CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
  CONFIG.Full_Flags_Reset_Value {0} \
  CONFIG.Input_Data_Width {32} \
  CONFIG.Input_Depth {32768} \
  CONFIG.Read_Data_Count {true} \
] [get_ips fifo_photon]
generate_target {instantiation_template synthesis simulation} [get_files ./src/ip/fifo_photon/fifo_photon.xci]

create_ip -name fifo_generator -vendor xilinx.com -library ip -version 13.2 -module_name normal_pmt_fifo -dir ./src/ip
set_property -dict [list \
  CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
  CONFIG.Input_Data_Width {32} \
  CONFIG.Read_Data_Count {true} \
] [get_ips normal_pmt_fifo]
generate_target {instantiation_template synthesis simulation} [get_files ./src/ip/normal_pmt_fifo/normal_pmt_fifo.xci]

create_ip -name fifo_generator -vendor xilinx.com -library ip -version 13.2 -module_name pulse_fifo -dir ./src/ip
set_property -dict [list \
  CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
  CONFIG.Input_Data_Width {32} \
  CONFIG.Input_Depth {512} \
  CONFIG.Output_Data_Width {64} \
  CONFIG.Performance_Options {First_Word_Fall_Through} \
  CONFIG.Read_Data_Count {true} \
] [get_ips pulse_fifo]
generate_target {instantiation_template synthesis simulation} [get_files ./src/ip/pulse_fifo/pulse_fifo.xci]

create_ip -name blk_mem_gen -vendor xilinx.com -library ip -version 8.4 -module_name pulser_ram -dir ./src/ip
set_property -dict [list \
  CONFIG.Enable_A {Always_Enabled} \
  CONFIG.Enable_B {Always_Enabled} \
  CONFIG.Memory_Type {Simple_Dual_Port_RAM} \
  CONFIG.Register_PortB_Output_of_Memory_Primitives {false} \
  CONFIG.Write_Depth_A {1024} \
  CONFIG.Write_Width_A {64} \
] [get_ips pulser_ram]
generate_target {instantiation_template synthesis simulation} [get_files ./src/ip/pulser_ram/pulser_ram.xci]

create_ip -name fifo_generator -vendor xilinx.com -library ip -version 13.2 -module_name readout_count_fifo -dir ./src/ip
set_property -dict [list \
  CONFIG.Fifo_Implementation {Independent_Clocks_Block_RAM} \
  CONFIG.Input_Data_Width {32} \
  CONFIG.Read_Data_Count {true} \
] [get_ips readout_count_fifo]
generate_target {instantiation_template synthesis simulation} [get_files ./src/ip/readout_count_fifo/readout_count_fifo.xci]

add_files -norecurse [glob ./src/*.vhd ./src/*.v]
set_property top photon [current_fileset]

add_files -fileset constrs_1 -norecurse ./constraints/xem7305.xdc

update_compile_order -fileset sources_1

puts "Project created at $PROJ_DIR/$PROJ_NAME.xpr — open in Vivado GUI or run synth_design/impl_design/write_bitstream from here."
